from functions.database.queries import generalQuery
from functions.manage_data.CRUD.format import format_data_total
from fastapi import HTTPException


def getDataTotal():
    # print("get data total")
    # CUU1A
    # data = generalQuery("SELECT VCC, CampaignId, ContactId, ContactName, ContactAddress, InteractionId, ImportId, Agent, ResultLevel1, ResultLevel2, ResultLevel3, ManagementResultCode, ManagementResultDescription, StartedManagement, TmStmp, Intentos, FechaAgendamiento, Telefono2, Observaciones, ID, IDENTIFICACION, NOMBRE_CLIENTE, PAIS, CIUDAD, ZONA, DIRECCION, ENTIDAD, AGENCIA, SECCION, PERIODO, AREA, USUARIO, TRANSACCION, CUENTA, FECHA_ATENCION, HORA_ATENCION, PREGUNTA_NPS, PREGUNTA_NPS_1, RESPUESTA_NPS, RESPUESTA_NPS_1, ATRIBUTO_NPS, PREGUNTA_INS, PREGUNTA_INS_1, RESPUESTA_INS, RESPUESTA_INS_1, ATRIBUTO_INS, PREGUNTA_CES, PREGUNTA_CES_1, RESPUESTA_CES, RESPUESTA_CES_1, ATRIBUTO_CES, PREGUNTA_4, PREGUNTA_4_1, PREGUNTA_5, PREGUNTA_5_1, PREGUNTA_6, PREGUNTA_6_1, PREGUNTA_7, PREGUNTA_7_1, PREGUNTA_8, PREGUNTA_8_1, PREGUNTA_9, PREGUNTA_9_1, PREGUNTA_10, PREGUNTA_10_1, PREGUNTA_11, PREGUNTA_11_1, PREGUNTA_12, PREGUNTA_12_1, PREGUNTA_13, PREGUNTA_13_1, RESPUESTA_4, RESPUESTA_4_1, RESPUESTA_5, RESPUESTA_5_1, RESPUESTA_6, RESPUESTA_6_1, RESPUESTA_7, RESPUESTA_7_1, RESPUESTA_8, RESPUESTA_8_1, RESPUESTA_9, RESPUESTA_9_1, RESPUESTA_10, RESPUESTA_10_1, RESPUESTA_11, RESPUESTA_11_1, RESPUESTA_12, RESPUESTA_12_1, RESPUESTA_13, RESPUESTA_13_1, ESTADO_AUDITORIA,TIPO_AGENCIA,PREGUNTA_AGILIDAD,PREGUNTA_AMABILIDAD,RESPUESTA_AMABILIDAD,RESPUESTA_AGILIDAD,RESPUESTA_AMABILIDAD_I,RESPUESTA_AGILIDAD_I  FROM data_encuestas_final")
    # data = generalQuery("SELECT VCC, CampaignId, ContactId, ContactName, ContactAddress, InteractionId, ImportId, Agent, ResultLevel1, ResultLevel2, ResultLevel3, ManagementResultCode, ManagementResultDescription, StartedManagement, TmStmp, Intentos, FechaAgendamiento, Telefono2, Observaciones, ID, IDENTIFICACION, NOMBRE_CLIENTE, PAIS, CIUDAD, ZONA, DIRECCION, ENTIDAD, AGENCIA, SECCION, PERIODO, AREA, USUARIO, TRANSACCION, GENERO, FECHA_ATENCION, HORA_ATENCION,PREGUNTA_NPS, PREGUNTA_NPS_1, RESPUESTA_NPS, RESPUESTA_NPS_1, ATRIBUTO_NPS, PREGUNTA_INS, PREGUNTA_INS_1, RESPUESTA_INS, RESPUESTA_INS_1, ATRIBUTO_INS, PREGUNTA_CES, PREGUNTA_CES_1, RESPUESTA_CES, RESPUESTA_CES_1, ATRIBUTO_CES, PREGUNTA_4, PREGUNTA_4_1, PREGUNTA_5, PREGUNTA_5_1, PREGUNTA_6, PREGUNTA_6_1, PREGUNTA_7, PREGUNTA_7_1, PREGUNTA_8, PREGUNTA_8_1, PREGUNTA_9, PREGUNTA_9_1, PREGUNTA_10, PREGUNTA_10_1, PREGUNTA_11, PREGUNTA_11_1, PREGUNTA_12, PREGUNTA_12_1, PREGUNTA_13, PREGUNTA_13_1, RESPUESTA_4, RESPUESTA_4_1, RESPUESTA_5, RESPUESTA_5_1, RESPUESTA_6, RESPUESTA_6_1, RESPUESTA_7, RESPUESTA_7_1, RESPUESTA_8, RESPUESTA_8_1, RESPUESTA_9, RESPUESTA_9_1, RESPUESTA_10, RESPUESTA_10_1, RESPUESTA_11, RESPUESTA_11_1, RESPUESTA_12, RESPUESTA_12_1, RESPUESTA_13, RESPUESTA_13_1, ESTADO_AUDITORIA,TIPO_AGENCIA,PREGUNTA_AGILIDAD,PREGUNTA_AMABILIDAD,RESPUESTA_AMABILIDAD,RESPUESTA_AGILIDAD,RESPUESTA_AMABILIDAD_I,RESPUESTA_AGILIDAD_I  FROM gestionfinal WHERE ResultLevel1 = 'CU1 ACEPTA OFERTA PRODUCTO'")
    data = generalQuery(
        "SELECT VCC, CampaignId, ContactId, ContactName, ContactAddress, InteractionId, ImportId, Agent, ResultLevel1, ResultLevel2, ResultLevel3, ManagementResultCode, ManagementResultDescription, StartedManagement, TmStmp, Intentos, FechaAgendamiento, Telefono2, Observaciones, ID, IDENTIFICACION, NOMBRE_CLIENTE, PAIS, CIUDAD, ZONA, DIRECCION, ENTIDAD, AGENCIA, SECCION, PERIODO, AREA, USUARIO, TRANSACCION, GENERO, FECHA_ATENCION, HORA_ATENCION,PREGUNTA_NPS, PREGUNTA_NPS_1, RESPUESTA_NPS, RESPUESTA_NPS_1, ATRIBUTO_NPS, PREGUNTA_INS, PREGUNTA_INS_1, RESPUESTA_INS, RESPUESTA_INS_1, ATRIBUTO_INS, PREGUNTA_CES, PREGUNTA_CES_1, RESPUESTA_CES, RESPUESTA_CES_1, ATRIBUTO_CES, PREGUNTA_4, PREGUNTA_4_1, PREGUNTA_5, PREGUNTA_5_1, PREGUNTA_6, PREGUNTA_6_1, PREGUNTA_7, PREGUNTA_7_1, PREGUNTA_8, PREGUNTA_8_1, PREGUNTA_9, PREGUNTA_9_1, PREGUNTA_10, PREGUNTA_10_1, PREGUNTA_11, PREGUNTA_11_1, PREGUNTA_12, PREGUNTA_12_1, PREGUNTA_13, PREGUNTA_13_1, RESPUESTA_4, RESPUESTA_4_1, RESPUESTA_5, RESPUESTA_5_1, RESPUESTA_6, RESPUESTA_6_1, RESPUESTA_7, RESPUESTA_7_1, RESPUESTA_8, RESPUESTA_8_1, RESPUESTA_9, RESPUESTA_9_1, RESPUESTA_10, RESPUESTA_10_1, RESPUESTA_11, RESPUESTA_11_1, RESPUESTA_12, RESPUESTA_12_1, RESPUESTA_13, RESPUESTA_13_1, ESTADO_AUDITORIA,TIPO_AGENCIA,PREGUNTA_AGILIDAD,PREGUNTA_AMABILIDAD,RESPUESTA_AMABILIDAD,RESPUESTA_AGILIDAD  FROM gestionfinal WHERE ResultLevel1 = 'CU1 ACEPTA OFERTA PRODUCTO'"
    )
    if data != None:
        formatted_data = format_data_total(data)
        # print(formatted_data)
        return formatted_data
    raise HTTPException(status_code=404, detail="Item not found")


def getColumnsDataTotal():
    columns = generalQuery("DESCRIBE `data_encuestas_final`")
    for col in columns:
        print(col[0])
        # print(col[0].lower())
    return columns
